name = "DynamicGlobalLocalShrinkage"
uuid = "95f0ba86-bb51-4e4e-bc21-89dc4565d801"
version = "1.0.0-DEV"
authors = ["Mattias Villani"]

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
PolyaGammaSamplers = "99ff7fc7-8a0f-4729-8284-81f1989d3fc6"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Utils = "a6a4a4df-ba9f-45e9-bafc-bec3296762b9"

[sources]
Utils = {rev = "main", url = "https://github.com/mattiasvillani/Utils.jl.git"}

[compat]
BandedMatrices = "1.9.4"
Colors = "0.13.1"
Distributions = "0.25.120"
LinearAlgebra = "1.11.0"
PDMats = "0.11.35"
PolyaGammaSamplers = "0.1.0"
SparseArrays = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.5"
Utils = "0.1.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
