[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
DynamicGlobalLocalShrinkage = "95f0ba86-bb51-4e4e-bc21-89dc4565d801"

[sources]
DynamicGlobalLocalShrinkage = {path = ".."}
